### ISSUE TITLE
Math variants not properly rendered for lowercase letters

### ISSUE THREAD

**Issue by eniraa** [0xpapercut/obsidian-wypst#3]
When doing something like `$bb(a)$` I'd expect it to render the same way as `$\mathbb{a}$`, but instead I get the default italic a.
<img width="699" alt="screenshot_20240223T150319-0500 png@2x" src="https://github.com/0xpapercut/obsidian-wypst/assets/47072520/b957ae27-34ec-4d6d-85ec-9bc6cd68714f">

**Comment by 0xpapercut** [comment]
Hello @eniraa , thanks for opening this issue! I'll look into this the first week of March (my exams are next week). This should be straightforward to fix, I'll keep you updated on it :).

**Comment by 0xpapercut** [comment]
KaTeX produces the italic "a" for `\mathbb{a}`, and as KaTeX itself is used as backend for Wypst I'm not sure if it's possible to fix this.

My philosophy has been to create special cases in the code just for standard behavior; and the fact that KaTeX does not recognise this syntax suggests it's somewhat non standard.

For now I'll focus on other issues; if you really need this, let me know.
