### ISSUE TITLE
Sets not working in Typst

### ISSUE THREAD

**Issue by eniraa** [0xpapercut/obsidian-wypst#4]
When attempting to type a set in Typst, this happens:
<img width="520" alt="screenshot_20240226T153447-0500 png@2x" src="https://github.com/0xpapercut/obsidian-wypst/assets/47072520/dd3bbbf1-3bcf-4718-b7ae-891b6e7ca521">

**Comment by 0xpapercut** [comment]
Thanks for posting this issue! I'm aware of this problem, this is probably an easy fix; the reason I haven't fixed it yet is because I'm having exams this week. I should be able to get this fixed by Thursday or Friday though, along all other open issues :)
