### ISSUE TITLE
Multiline math blocks don't work

### ISSUE THREAD

**Issue by Ellpeck** [0xpapercut/obsidian-wypst#5]
Hi! I love this plugin and how easy it is to use without requiring any complicated settings!! ❤️ 

I'm encountering an issue though: using multiline math like
```
$$
Q = rho A v + "time offset"
$$
```

causes

![image](https://github.com/0xpapercut/obsidian-wypst/assets/5741138/893d27c2-b434-4f04-9d23-37a9ff01fbdb)

to be displayed. I usually format bigger math like described above, so it would be awesome if this plugin could support it :)

**Comment by 0xpapercut** [comment]
Hello @Ellpeck, thank you for opening this issue! I will start working on this on Friday.
